apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  # No es necesario poner el namespace aquí si lo forzamos en el kustomization
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
